import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { ArrowDown01Icon as ChevronDown, } from 'hugeicons-react';
import { SummaryCard } from '../components/SummaryCard';
import { TrendChart } from '../components/TrendChart';
import { RecentAnomaliesList } from '../components/RecentAnomalies';
import { RecentIncidentsList } from '../components/RecentIncidents';
export const Dashboard = () => {
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, className: "p-6 md:p-10 space-y-10 min-h-screen bg-surface-base overflow-x-hidden", children: [_jsxs("div", { className: "flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 px-2", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-4xl font-black text-zinc-900 tracking-tight", children: "System Pulse" }), _jsx("p", { className: "text-zinc-500 text-xs mt-2 font-bold uppercase tracking-[0.2em] opacity-60", children: "Global Autonomous Dashboard" })] }), _jsxs(motion.button, { whileHover: { scale: 1.02 }, whileTap: { scale: 0.98 }, className: "flex items-center gap-3 px-6 py-3.5 bg-surface-white border border-border-default rounded-xl text-xs font-black text-zinc-600 uppercase tracking-widest hover:bg-zinc-50 hover:border-border-default md-elevation-1 hover:md-elevation-2 md-transition", children: ["Context Node", _jsx(ChevronDown, { className: "w-4 h-4 text-zinc-400" })] })] }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-6", children: [_jsx(SummaryCard, { label: "Throughput Today", value: "1.2M", trend: "+12%", trendType: "positive" }), _jsx(SummaryCard, { label: "Active Signals", value: "18", trend: "+2", trendType: "negative" }), _jsx(SummaryCard, { label: "Active Incidents", value: "4", trend: "-1", trendType: "positive" }), _jsx(SummaryCard, { label: "Resolution Delta", value: "12", trend: "+5", trendType: "positive" })] }), _jsxs("div", { className: "bg-surface-white rounded-2xl border border-border-subtle p-6 md:p-8 md-elevation-1 hover:md-elevation-2 md-transition", children: [_jsxs("div", { className: "flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12 px-2", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-2xl font-black text-zinc-900 tracking-tight", children: "System Dynamics" }), _jsx("p", { className: "text-xs font-bold text-zinc-400 uppercase tracking-widest mt-2", children: "Real-time throughput telemetry" })] }), _jsx("div", { className: "flex items-center gap-2 p-1.5 bg-zinc-50 rounded-xl border border-border-subtle overflow-x-auto", children: ['24h', '7 days', '30 days'].map((period) => (_jsx("button", { className: "px-5 py-2.5 rounded-lg text-xs font-black text-zinc-400 uppercase tracking-widest hover:text-zinc-900 md-transition active:scale-95 whitespace-nowrap", children: period }, period))) })] }), _jsx("div", { className: "h-[400px] min-h-[300px] w-full", children: _jsx(TrendChart, {}) })] }), _jsxs("div", { className: "grid grid-cols-1 xl:grid-cols-2 gap-8 pb-12", children: [_jsx(RecentAnomaliesList, {}), _jsx(RecentIncidentsList, {})] })] }));
};
