import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Search01Icon as Search, Database01Icon as Database, ArrowDown01Icon as ChevronDown, Calendar01Icon as Calendar, Activity01Icon as Activity } from 'hugeicons-react';
import { cn } from '../utils/cn';
export const AnomalyFilters = ({ searchTerm, setSearchTerm, statusFilter, setStatusFilter, severityFilter, setSeverityFilter, }) => {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs(motion.div, { initial: { opacity: 0, y: -10 }, animate: { opacity: 1, y: 0 }, className: "bg-surface-white p-2 rounded-xl border border-border-subtle flex flex-col lg:flex-row items-stretch lg:items-center gap-4 md-elevation-1 focus-within:md-elevation-2 md-transition", children: [_jsxs("div", { className: "relative flex-1 group", children: [_jsx(Search, { className: "absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400 w-4 h-4 group-focus-within:text-primary-600 md-transition" }), _jsx(motion.input, { whileHover: { scale: 1.005 }, type: "text", placeholder: "Search by ID, keyword, or node...", className: "w-full pl-11 pr-4 py-2.5 bg-zinc-50 border border-transparent rounded-lg text-sm text-zinc-700 font-normal placeholder:text-zinc-400 focus:outline-none focus:bg-surface-white focus:border-primary-200 focus:shadow-sm md-transition md-focus-ring", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value) })] }), _jsxs("div", { className: "flex flex-wrap items-center gap-2 pr-2", children: [_jsx("div", { className: "flex bg-zinc-50 p-1 rounded-lg border border-border-subtle", children: ['All', 'Open', 'Acknowledged', 'Resolved'].map((s) => (_jsx(motion.button, { whileTap: { scale: 0.96 }, onClick: () => setStatusFilter(s), className: cn("px-4 py-1.5 text-[11px] font-bold uppercase tracking-wider rounded-md transition-all", statusFilter === s
                                        ? "bg-surface-white text-primary-600 shadow-sm border border-border-subtle"
                                        : "text-zinc-500 hover:text-zinc-700"), children: s }, s))) }), _jsx("div", { className: "bg-zinc-50 p-1 rounded-lg border border-border-subtle flex", children: ['All', 'Critical', 'High', 'Medium', 'Low'].map((sev) => (_jsx(motion.button, { whileTap: { scale: 0.96 }, onClick: () => setSeverityFilter(sev), className: cn("px-4 py-1.5 text-[11px] font-bold uppercase tracking-wider rounded-md transition-all", severityFilter === sev
                                        ? "bg-surface-white text-primary-600 shadow-sm border border-border-subtle"
                                        : "text-zinc-500 hover:text-zinc-700"), children: sev }, sev))) }), _jsxs(motion.button, { whileHover: { y: -1 }, whileTap: { scale: 0.98 }, className: "flex items-center gap-2 px-4 py-2 bg-surface-white border border-zinc-200 rounded-lg text-zinc-700 text-xs font-bold uppercase tracking-widest hover:bg-zinc-50 transition-all md-elevation-1", children: [_jsx(Database, { className: "w-3.5 h-3.5 text-primary-600" }), _jsx("span", { children: "Host" }), _jsx(ChevronDown, { className: "w-3.5 h-3.5 opacity-50" })] }), _jsxs(motion.button, { whileHover: { y: -1 }, whileTap: { scale: 0.98 }, className: "flex items-center gap-2 px-4 py-2 bg-primary-600 text-white rounded-lg text-xs font-bold uppercase tracking-widest hover:bg-primary-700 transition-all md-elevation-1 shadow-lg shadow-primary-500/20", children: [_jsx(Calendar, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "Timeline" })] })] })] }), _jsxs("div", { className: "flex items-center gap-4 px-2", children: [_jsxs("div", { className: "flex items-center gap-2 text-[10px] font-bold text-zinc-400 uppercase tracking-widest leading-none", children: [_jsx(Activity, { className: "w-3 h-3 text-primary-600" }), "AI Heuristic Correlation active"] }), _jsx(motion.div, { initial: { scaleX: 0 }, animate: { scaleX: 1 }, className: "h-px flex-1 bg-border-subtle origin-left" }), _jsx("p", { className: "text-[10px] font-bold text-zinc-300 uppercase tracking-[0.2em] leading-none", children: "Heuristic v2.4a" })] })] }));
};
