import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink } from 'react-router-dom';
import { motion } from 'framer-motion';
import { DashboardSquare01Icon as DashboardIcon, ListViewIcon as LogsIcon, Activity01Icon as AnomaliesIcon, AlertCircleIcon as IncidentsIcon, Database01Icon as DatabaseIcon, Analytics01Icon as HealthSignalIcon, Settings02Icon as SettingsIcon, Logout01Icon } from 'hugeicons-react';
import { cn } from '../utils/cn';
const NavItem = ({ icon: Icon, label, to }) => (_jsx(motion.div, { whileHover: { x: 4 }, whileTap: { scale: 0.98 }, className: "mx-4 mb-2", children: _jsxs(NavLink, { to: to, className: ({ isActive }) => cn("flex items-center gap-4 px-5 py-3.5 rounded-2xl md-transition group w-full relative overflow-hidden", isActive
            ? "bg-primary-600 text-white font-black md-elevation-3 shadow-xl shadow-primary-500/20"
            : "text-zinc-500 hover:bg-zinc-50 hover:text-zinc-900 font-black uppercase tracking-[0.1em] text-xs"), children: [_jsx(motion.div, { whileHover: { scale: 1.1, rotate: 5 }, transition: { type: "spring", stiffness: 400, damping: 10 }, className: "relative z-10", children: _jsx(Icon, { className: "w-5 h-5 flex-shrink-0" }) }), _jsx("span", { className: "relative z-10 whitespace-nowrap", children: label }), _jsx(motion.div, { className: "absolute inset-0 bg-gradient-to-r from-primary-400/0 to-primary-400/20 opacity-0 group-hover:opacity-100 md-transition", initial: false })] }) }));
export const Sidebar = ({ isOpen }) => {
    return (_jsxs("aside", { className: cn("bg-surface-white flex flex-col transition-all duration-500 relative z-20 h-full border-r border-border-subtle shadow-2xl shadow-zinc-200/50", isOpen ? "w-[320px]" : "w-0 overflow-hidden"), children: [_jsx("div", { className: "p-10 pb-6 flex items-center gap-5", children: _jsx("img", { src: "/debbie.PNG", alt: "Stratos Network AI", className: "h-20 w-auto object-contain md-transition hover:scale-105" }) }), _jsxs("div", { className: "px-10 py-10 flex items-center gap-5", children: [_jsx("div", { className: "w-16 h-16 rounded-2xl overflow-hidden border border-border-subtle md-elevation-1 flex-shrink-0 p-1.5 bg-zinc-50 shadow-inner group", children: _jsx("img", { src: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin", alt: "Admin", className: "w-full h-full object-cover rounded-xl bg-white md-transition group-hover:scale-110" }) }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "font-black text-zinc-900 text-base truncate tracking-tight uppercase", children: "McVeigh.K" }), _jsxs("div", { className: "flex items-center gap-2 mt-2", children: [_jsx("div", { className: "w-2 h-2 rounded-full bg-success-500 animate-pulse shadow-sm shadow-success-500/50" }), _jsx("span", { className: "text-[10px] font-black text-success-600 uppercase tracking-widest leading-none opacity-80", children: "Active Node" })] })] })] }), _jsx("div", { className: "h-px bg-border-subtle mx-10 mb-8 opacity-50" }), _jsx("div", { className: "flex-1 overflow-y-auto mt-2 custom-scrollbar no-scrollbar pb-10", children: _jsxs("div", { className: "space-y-1", children: [_jsx(NavItem, { icon: DashboardIcon, label: "Neural Hub", to: "/" }), _jsx(NavItem, { icon: LogsIcon, label: "Packet Streams", to: "/logs" }), _jsx(NavItem, { icon: AnomaliesIcon, label: "Signal Analysis", to: "/anomalies" }), _jsx(NavItem, { icon: IncidentsIcon, label: "Triage Unit", to: "/incidents" }), _jsx(NavItem, { icon: DatabaseIcon, label: "Knowledge", to: "/kb" }), _jsx(NavItem, { icon: HealthSignalIcon, label: "Core Vitals", to: "/health" }), _jsx(NavItem, { icon: SettingsIcon, label: "Parameters", to: "/settings" })] }) }), _jsx("div", { className: "p-6 bg-surface-base/30 border-t border-border-subtle", children: _jsxs(motion.button, { whileHover: { backgroundColor: 'var(--color-surface-white)', color: 'var(--color-critical-600)', borderColor: 'var(--color-critical-500)' }, whileTap: { scale: 0.98 }, className: "w-full flex items-center justify-center gap-4 px-5 py-5 text-zinc-400 rounded-2xl md-transition font-black uppercase tracking-[0.2em] text-xs border border-transparent hover:md-elevation-3 active:md-elevation-1 shadow-sm", children: [_jsx(Logout01Icon, { className: "w-5 h-5 opacity-40 group-hover:opacity-100" }), _jsx("span", { children: "Kill Switch" })] }) })] }));
};
